module Rubyc
  self.@logger: Logger

  RUBY_EXTENSION: ".rb"

  RUBYC_EXTENSION: ".rbc"

  class Error < StandardError
  end

  def self.version: () -> String

  def self.suffixes: () -> ::Array[".rbc"]

  def self.load: ((String|Pathname) input_path, ?load_path: (String|Pathname)?) -> bool

  def self.generate: ((String|Pathname) input_path, ?package_name: String?, ?record_dir_path: (String|Pathname)) -> String

  def self.logger: () -> Logger
end
